### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Kaltsoon** [tom2lua/reminder#1]
# Code review

Here's a short code review for you @tom2lua

### What did I do?

- Signed up
- Created a couple of events and did some modifications
- Checked the my events page
- Checked the calender page
- Checked the settings page and changed my settings
- Checked the dashboard and played around with the filters
- Signed out

### Experience

- Generally the user experience is really good, UI is clean as everything is really easy and intuitive to use
- Being able to change the UI theme is a very nice touch. Especially being able to use the dark theme is awesome 🌑
- Changing the hour format in user's settings is a really handy feature especially for people like me who are more used to the 24 hour format
- Should something happend after clicking a date in the [calendar page](https://amazing-shirley-0738ea.netlify.com/#/reminder/calendar)? Now it only shows a blank space
- Is there something wront with the "Show Events till" filter in the dashboard page? Today is 6th of March and event at 16th of March does not appear on the list when filtering events till next month
- Vue favicon is pretty cool, but maybe e.g. a calendar icon could be more suitable for this app

## Code

- Front end code is well structured, even a React developer such as I got a hang of it quickly
- Good call to use CSS variables with the theming
- Back end code is also well structured
- You can use the [express-async-errors](https://www.npmjs.com/package/express-async-errors) library to avoid the endless `try {} catch {}` blocks
- You could extract [access token decoding](https://github.com/tom2lua/reminder-backend/blob/master/controllers/events.js#L19) as well as [the authorization check](https://github.com/tom2lua/reminder-backend/blob/master/controllers/events.js#L21) into its own middleware. The result could be something like this:

```javascript
eventsRouter.get('/', authorize(), async (request, response, next) => {
  const events = await Event.find({ user: req.authorizedUser.id }).populate(
    'eventType',
    { name: 1, iconClass: 1, representColor: 1, cssClass: 1 }
  );

  response.json(events);
});
```

## Summary

- Easy to use app with clean user interface and good set of useful features. Good job!
- Code is clean and well structured without any major issuses

**Comment by tom2lua** [comment]
Hi Kalle,

Just to make sure, you are the teacher from UoH that evaluate my project,
right?

If so, thank you for your time and help, really appreciate your feedback. I
am aware of the issues you mentioned and I will try and fix them in
the future if I have time.

Again, thank you so much!

Best regards,
Nguyen Tran

**Comment by Kaltsoon** [comment]
Yes, that's right, maybe I should have mentioned that. :) The suggested changes are _optional_. The current state of your project is definitely enough for the credits. Good job!

**Comment by tom2lua** [comment]
Yes you should have, I was wondering who you are :) But everything is ok
now. Thank you so much for your help!

**Comment by tom2lua** [comment]
Hello Kalle,

Is it mean that you already finishing grading my project? If so, can you
give me the instructions on how to take credits from this course?
Thank you.

Best regards,
Nguyen Tran

Vào Th 6, 13 thg 3, 2020 vào lúc 10:31 Kalle Ilves <
notifications@github.com> đã viết:
